package OJ;

/**
 * Created by Tongzhenguo on 2017/6/13.
 Write a program to find the nth super ugly number.

 Super ugly numbers are positive numbers　whose all prime factors are in the given prime list primes of size k.
 For example, [1, 2, ４, 7, 8, 13, 14, 16, 19, 26, 28, 32] is the sequence of the first 12 super ugly numbers given primes = [2, 7, 13, 19] of size 4.

 Note:
 (1) 1 is a super ugly number for any given primes.
 (2) The given numbers in primes are in ascending order.
 (3) 0 < k ≤ 100, 0 < n ≤ 106, 0 < primes[i] < 1000.
 (4) The nth super ugly number is guaranteed to fit in a 32-bit signed integer.
 */
public class Super_Ugly_Number {
    /*
    * new ugly number is generated by multiplying a prime with previous generated ugly number. One catch is need to remove duplicate
    *
    * */
    public int nthSuperUglyNumberI(int n, int[] primes) {
        int[] ugly = new int[n];
        int[] idx = new int[primes.length];

        ugly[0] = 1;
        for (int i = 1; i < n; i++) {
            //find next
            ugly[i] = Integer.MAX_VALUE;
            for (int j = 0; j < primes.length; j++)
                ugly[i] = Math.min(ugly[i], primes[j] * ugly[idx[j]]);

            //slip duplicate
            for (int j = 0; j < primes.length; j++) {
                while (primes[j] * ugly[idx[j]] <= ugly[i]) idx[j]+=1;
            }
        }

        return ugly[n - 1];
    }

    public static void main(String[] args) {

        Super_Ugly_Number super_ugly_number = new Super_Ugly_Number();
        for(int i=1;i<12;i++ ){
            super_ugly_number.nthSuperUglyNumberI(i,new int[]{2, 7, 13, 19} );
        }


    }

}
